### ISSUE TITLE
Remove dependency on Atlas

### ISSUE THREAD

**Issue by idmontie** [gios-asu/gios-vagrant#8]

**Comment by chasethenag420** [comment]
Any alternative location to store the box? Currently I uploaded to https://atlas.hashicorp.com/ a place where we can find all the existing boxes uploaded by officials vendors and other community members.
`https://atlas.hashicorp.com/boxes/search?page=1`.

**Comment by chasethenag420** [comment]
Instead of creating a box image of `gios.box` itself we can use base ubunutu 14.04 and provision it with our required setup to be present on the top of base image. This is much faster than creating an image and we have flexibility of updating and run provision script on demand basis. This way we no need to host or create an image. The best thing is provisioning script will not be required to be run again unless we destroy or force the vagrant to re-run provision script. Any packages which are already installed with previous run of provision script will not be installed again which speeds up rerunning provision script to add more stuff. So it works the same way as we have gios.box until we destroy vagrant. Once we destroy box provisioning script will run again to bring up. We can handle that suspend and resuming vagrant instead of destroy.

**Comment by chasethenag420** [comment]
# Having gios box

## Pros
- Download image and play.
- Faster to get environment ready.
- Simple to distribute.
- No discrepancy in working environment among different members using same image.
- Auto check for new version of image before bringing up vagrant machine which can ensure every one is up to date.
- Minimal amount configuration set-up needed to customize.
- Can destroy image any time and pull new one on the go.
- Add new packages to current box through simple ssh.

## Cons
- Place to host image.
- Managing account for host image.
- Recreating and pushing image for every small change in package which requires build from starting.
- Steps taken to change base via ssh should be repeated every time we destroy vagrant machine and create again.
- Packer is required on host machine if we have to build new box.

# Setting up gios env with base box

## Pros
- Clone git hub repo and play with box  by doing `vagrant up`.
- Easy to add new packages or update settings for the box working on and will not be back in few seconds.
- Pulling latest git hub code can be done simply by re-provisioning.
- Simpler to distribute.
- No hosting needed.
- No new account management needed.
- Each member can have a different working environment for their flexibility or to try out new changes by using new updating few packages.
- Being up to date with other team members just requires pull this repo and doing `vagrant reload --provision`
- Packages installed before will not be reinstalled which saves time to get new changes.

## Cons
- Requires git on host machine
- There could be difference in working environment among different team members which can depend on the time of their install as every time provision script is run it will try to pull the latest version available(eg. wordpress or php5).
- Git clone via re-provisioning can override the changes you have local if changes are not committed.
- First install will take time to download base image.
- Provisioning time every time only need time to install latest updates.

# Hybrid of above two ways.. having both image as well as provision script.
